"use client";

import { CalendarDays, ChevronLeft, ChevronRight, Eye, History, LoaderCircle, Menu, Search, UserRound, X } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";

type Option = { value: string; label: string };
type AuditEvent = { id:string;entity_type:string;entity_id:string|null;action:string;details:Record<string,unknown>;created_at:string;actor_id:string|null;actor_name:string|null;actor_email:string|null };
type Payload = { events:AuditEvent[];pagination:{page:number;pageSize:number;total:number;pages:number};summary:{total:number;today:number;actors:number;entities:Option[];actions:Option[];actor_options:Option[]} };

const entityLabels: Record<string,string> = { work_order:"Orçamento / ordem",customers:"Cliente",vehicles:"Veículo",products:"Produto / serviço",mechanics:"Mecânico",suppliers:"Fornecedor",supplier:"Fornecedor",receivable:"Conta a receber",payable:"Conta a pagar",purchase:"Compra",inventory_movement:"Movimento de estoque",financial_transaction:"Movimento financeiro",financial_account:"Conta financeira",payment_method:"Forma de pagamento",financial_category_group:"Grupo financeiro",financial_category:"Categoria financeira",app_user:"Usuário",company:"Empresa" };
const actionLabels: Record<string,string> = { created:"Criado",updated:"Alterado",paid:"Pago",reopened:"Reaberto",status_changed:"Status alterado",shared:"Compartilhado",follow_up:"Retorno registrado",duplicated:"Nova versão criada",login:"Login realizado",impersonation_started:"Acesso administrativo" };
const fieldLabels: Record<string,string> = { name:"Nome",email:"E-mail",role:"Papel",permissions:"Permissões",active:"Ativo",passwordChanged:"Senha alterada",orderNumber:"Orçamento",order_number:"Orçamento",customer:"Cliente",customerName:"Cliente",previousCustomer:"Cliente anterior",total:"Total",previousTotal:"Total anterior",status:"Status",amount:"Valor",date:"Data",dueDate:"Vencimento",competenceDate:"Competência",description:"Descrição",channel:"Canal",outcome:"Resultado",next_follow_up_at:"Próximo retorno",companyName:"Empresa",share_count:"Quantidade de envios",productName:"Produto",quantity:"Quantidade",previousBalance:"Saldo anterior",balance:"Novo saldo",before:"Antes",after:"Depois" };
const dateTime = new Intl.DateTimeFormat("pt-BR", { dateStyle:"short", timeStyle:"short" });

function displayValue(value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "Sim" : "Não";
  if (Array.isArray(value)) return value.join(", ") || "—";
  if (typeof value === "object") return Object.entries(value as Record<string,unknown>).map(([key,item]) => `${fieldLabels[key] ?? key}: ${displayValue(item)}`).join(" · ");
  return String(value);
}

export function AuditPage() {
  const [payload,setPayload]=useState<Payload|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [mobileMenu,setMobileMenu]=useState(false); const [selected,setSelected]=useState<AuditEvent|null>(null);
  const [search,setSearch]=useState(""); const [entity,setEntity]=useState(""); const [action,setAction]=useState(""); const [actor,setActor]=useState(""); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [page,setPage]=useState(1);
  const query=useMemo(()=>{const params=new URLSearchParams({page:String(page),pageSize:"50"});if(search.trim())params.set("search",search.trim());if(entity)params.set("entity",entity);if(action)params.set("action",action);if(actor)params.set("actor",actor);if(from)params.set("from",from);if(to)params.set("to",to);return params.toString();},[search,entity,action,actor,from,to,page]);
  const load=useCallback((signal?:AbortSignal)=>{setLoading(true);setError("");fetch(`/api/audit?${query}`,{signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error??"Não foi possível carregar a auditoria.");setPayload(data);}).catch(caught=>{if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}).finally(()=>setLoading(false));},[query]);
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>load(controller.signal),search?350:0);return()=>{clearTimeout(timer);controller.abort();};},[load,search]);
  const changeFilter=(setter:(value:string)=>void)=>(value:string)=>{setter(value);setPage(1);};
  const clear=()=>{setSearch("");setEntity("");setAction("");setActor("");setFrom("");setTo("");setPage(1);};
  return <div className="app-shell"><AppSidebar active="auditoria"/><main className="workspace registry-workspace"><header className="topbar registry-topbar"><button className="mobile-menu" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Abrir menu"><Menu/></button><div><p className="eyebrow">SEGURANÇA OPERACIONAL</p><h1>Auditoria</h1><p className="page-description">Consulte quem alterou cada informação, quando e o conteúdo registrado na ação.</p></div></header>{mobileMenu&&<div className="mobile-shortcuts registry-shortcuts"><Link href="/">Atendimento</Link><Link href="/auditoria">Auditoria</Link></div>}
    <section className="operations-stats audit-stats"><div><History/><span>Eventos registrados</span><strong>{payload?.summary.total??0}</strong></div><div><CalendarDays/><span>Alterações hoje</span><strong>{payload?.summary.today??0}</strong></div><div><UserRound/><span>Usuários identificados</span><strong>{payload?.summary.actors??0}</strong></div></section>
    <section className="audit-filters"><label className="audit-search"><Search size={17}/><input placeholder="Buscar usuário, ação ou conteúdo..." value={search} onChange={event=>changeFilter(setSearch)(event.target.value)}/></label><label><span>Módulo</span><select value={entity} onChange={event=>changeFilter(setEntity)(event.target.value)}><option value="">Todos</option>{payload?.summary.entities.map(option=><option key={option.value} value={option.value}>{entityLabels[option.label]??option.label}</option>)}</select></label><label><span>Ação</span><select value={action} onChange={event=>changeFilter(setAction)(event.target.value)}><option value="">Todas</option>{payload?.summary.actions.map(option=><option key={option.value} value={option.value}>{actionLabels[option.label]??option.label}</option>)}</select></label><label><span>Usuário</span><select value={actor} onChange={event=>changeFilter(setActor)(event.target.value)}><option value="">Todos</option><option value="system">Sistema / importação</option>{payload?.summary.actor_options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label><span>De</span><input type="date" value={from} onChange={event=>changeFilter(setFrom)(event.target.value)}/></label><label><span>Até</span><input type="date" value={to} onChange={event=>changeFilter(setTo)(event.target.value)}/></label><button className="text-button" onClick={clear}>Limpar filtros</button></section>
    <section className="registry-panel audit-panel">{loading?<div className="registry-loading"><LoaderCircle className="spin"/>Carregando histórico...</div>:error?<div className="empty-state">{error}</div>:!payload?.events.length?<div className="empty-state">Nenhuma alteração encontrada com estes filtros.</div>:<div className="registry-table-wrap"><table className="registry-table audit-table"><thead><tr><th>Data e hora</th><th>Usuário</th><th>Módulo</th><th>Ação</th><th>Resumo</th><th>Detalhes</th></tr></thead><tbody>{payload.events.map(event=><tr key={event.id}><td data-label="Data">{dateTime.format(new Date(event.created_at))}</td><td data-label="Usuário"><strong>{event.actor_name??"Sistema / importação"}</strong>{event.actor_email&&<small className="table-note">{event.actor_email}</small>}</td><td data-label="Módulo">{entityLabels[event.entity_type]??event.entity_type}</td><td data-label="Ação"><span className="audit-action">{actionLabels[event.action]??event.action}</span></td><td data-label="Resumo" className="audit-summary">{Object.entries(event.details??{}).slice(0,2).map(([key,value])=>`${fieldLabels[key]??key}: ${displayValue(value)}`).join(" · ")||"Sem informações adicionais"}</td><td data-label="Detalhes"><button className="table-action" onClick={()=>setSelected(event)}><Eye size={15}/>Ver</button></td></tr>)}</tbody></table></div>}</section>
    {payload&&payload.pagination.pages>1&&<nav className="audit-pagination" aria-label="Paginação"><button disabled={page<=1} onClick={()=>setPage(current=>current-1)}><ChevronLeft size={17}/>Anterior</button><span>Página {payload.pagination.page} de {payload.pagination.pages} · {payload.pagination.total} resultado(s)</span><button disabled={page>=payload.pagination.pages} onClick={()=>setPage(current=>current+1)}>Próxima<ChevronRight size={17}/></button></nav>}
  </main>{selected&&<div className="modal-backdrop"><section className="registry-modal audit-modal"><header className="modal-header"><div><span className="section-kicker">DETALHES DA ALTERAÇÃO</span><h2>{actionLabels[selected.action]??selected.action}</h2></div><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Fechar"><X/></button></header><div className="audit-detail"><div className="audit-detail-meta"><span><b>Data</b>{dateTime.format(new Date(selected.created_at))}</span><span><b>Responsável</b>{selected.actor_name??"Sistema / importação"}</span><span><b>Módulo</b>{entityLabels[selected.entity_type]??selected.entity_type}</span></div>{Object.entries(selected.details??{}).length?<dl>{Object.entries(selected.details).map(([key,value])=><div key={key}><dt>{fieldLabels[key]??key}</dt><dd>{displayValue(value)}</dd></div>)}</dl>:<p className="empty-state">Esta ação não possui informações adicionais.</p>}</div></section></div>}</div>;
}
