"use client";
import { AlertTriangle, Building2, CheckCircle2, Eye, KeyRound, LoaderCircle, LogOut, Plus, ShieldCheck, Users, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

type Company = { id:string; name:string; slug:string; active:boolean; created_at:string; user_count:number; admin_count:number; admin_user_id?:string; admin_email?:string };
export function CompaniesAdminPage() {
  const [companies,setCompanies]=useState<Company[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [modal,setModal]=useState<"create"|"credentials"|undefined>(); const [selected,setSelected]=useState<Company>(); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
  async function load(){const response=await fetch("/api/admin/companies");const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível carregar as empresas.");setCompanies(payload.companies);}
  useEffect(()=>{const controller=new AbortController();fetch("/api/admin/companies",{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível carregar as empresas.");setCompanies(payload.companies);}).catch(caught=>{if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[]);
  function openCreate(){setModal("create");setSelected(undefined);setName("");setEmail("");setPassword("");setError("");} function openCredentials(company:Company){setModal("credentials");setSelected(company);setEmail(company.admin_email??"");setPassword("");setError("");}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const url=modal==="create"?"/api/admin/companies":`/api/admin/companies/${selected!.id}`;const response=await fetch(url,{method:modal==="create"?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(modal==="create"?{name,email:email||undefined,password:password||undefined}:{action:"credentials",email,password:password||undefined})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível salvar.");const wasExisting=Boolean(selected?.admin_count);await load();setModal(undefined);setNotice(modal==="create"?"Empresa criada com ambiente isolado.":wasExisting?"Login administrativo atualizado.":"Acesso administrativo definido.");}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível salvar.");}finally{setSaving(false);}}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.assign("/login");}
  async function impersonate(company:Company){setError("");try{const response=await fetch("/api/auth/impersonation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyId:company.id})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível abrir o painel.");window.location.assign("/");}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível abrir o painel.");}}
  return <main className="platform-admin"><header className="platform-header"><div className="platform-brand"><span><ShieldCheck/></span><div><p>ADMINISTRAÇÃO DA PLATAFORMA</p><h1>Empresas</h1></div></div><div className="platform-actions"><button className="secondary-button" onClick={logout}><LogOut size={17}/> Sair</button><button className="primary-button" onClick={openCreate}><Plus size={18}/> Nova empresa</button></div></header><section className="platform-summary"><div><Building2/><span>Empresas</span><strong>{companies.length}</strong></div><div><CheckCircle2/><span>Ativas</span><strong>{companies.filter(item=>item.active).length}</strong></div><div><Users/><span>Usuários</span><strong>{companies.reduce((sum,item)=>sum+Number(item.user_count),0)}</strong></div><div className="warning"><AlertTriangle/><span>Sem acesso definido</span><strong>{companies.filter(item=>!item.admin_count).length}</strong></div></section>
  <section className="company-grid">{loading?<div className="registry-loading"><LoaderCircle className="spin"/>Carregando empresas...</div>:companies.map(company=><article className={`company-card ${!company.admin_count?"needs-login":""}`} key={company.id}><header><div className="company-icon"><Building2/></div><span className={`registry-status ${company.active?"active":"inactive"}`}>{company.active?"Ativa":"Inativa"}</span></header><h2>{company.name}</h2><p className="company-slug">{company.slug}</p><div className="company-meta"><span><Users size={16}/>{company.user_count} usuário(s)</span>{company.admin_count?<span><KeyRound size={16}/>{company.admin_email}</span>:<span className="missing-access"><AlertTriangle size={16}/>Login administrativo pendente</span>}</div><div className="company-card-actions"><button className="secondary-button" onClick={()=>void impersonate(company)} disabled={!company.active}><Eye size={17}/>Visualizar painel</button><button className="primary-button" onClick={()=>openCredentials(company)}><KeyRound size={17}/>{company.admin_count?"Alterar login e senha":"Definir login e senha"}</button></div></article>)}{!loading&&!companies.length&&<div className="empty-state">Nenhuma empresa cadastrada.</div>}</section>{error&&!modal&&<p className="platform-error">{error}</p>}
  {modal&&<div className="modal-backdrop"><section className="registry-modal"><header className="modal-header"><div><span className="section-kicker">MULTI-TENANT</span><h2>{modal==="create"?"Nova empresa":selected?.admin_count?"Alterar acesso":"Definir acesso"}</h2></div><button className="icon-button" onClick={()=>setModal(undefined)}><X/></button></header><form className="registry-form" onSubmit={save}>{modal==="credentials"&&<p className="tenant-callout"><Building2/><span>O acesso será vinculado exclusivamente à empresa <b>{selected?.name}</b>.</span></p>}<div className="form-grid registry-form-grid">{modal==="create"&&<label className="field span-2"><span>Nome da empresa *</span><input value={name} onChange={event=>setName(event.target.value)} required autoFocus/></label>}<label className="field"><span>E-mail administrativo {modal==="create"&&"(opcional)"}</span><input type="email" value={email} onChange={event=>setEmail(event.target.value)} required={modal==="credentials"}/></label><label className="field"><span>{modal==="credentials"&&selected?.admin_count?"Nova senha (opcional)":"Senha"} {modal==="create"&&"(opcional)"}</span><input type="password" minLength={8} value={password} onChange={event=>setPassword(event.target.value)} required={modal==="credentials"&&!selected?.admin_count}/></label></div>{modal==="create"?<p className="form-help">Você pode criar a empresa agora e definir o acesso posteriormente.</p>:selected?.admin_count&&<p className="form-help">Deixe a senha vazia para manter a senha atual.</p>}{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setModal(undefined)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?<LoaderCircle className="spin" size={18}/>:<CheckCircle2 size={18}/>}Salvar</button></footer></form></section></div>}{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}</main>;
}
