"use client";

import { CheckCircle2, Layers3, LoaderCircle, Menu, Pencil, Plus, Tags, X } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";

type Nature="RECEITA"|"DESPESA"|"AMBOS";
type Category={id:string;groupId:string;name:string;nature:Nature;includeInDrg:boolean;systemCode?:string;active:boolean};
type Group={id:string;name:string;nature:Nature;includeInDrg:boolean;systemCode?:string;active:boolean;categories:Category[]};
type Editing={entity:"group"|"category";id?:string;systemCode?:string};

export function FinancialCategoriesPage(){
  const [groups,setGroups]=useState<Group[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [mobileMenu,setMobileMenu]=useState(false);const [editing,setEditing]=useState<Editing>();
  const [name,setName]=useState("");const [nature,setNature]=useState<Nature>("DESPESA");const [groupId,setGroupId]=useState("");const [includeInDrg,setIncludeInDrg]=useState(true);const [active,setActive]=useState(true);
  async function load(signal?:AbortSignal){const response=await fetch("/api/financial-categories",{signal});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível carregar as categorias.");setGroups(payload.groups);}
  useEffect(()=>{const controller=new AbortController();fetch("/api/financial-categories",{signal:controller.signal}).then(async(response)=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível carregar as categorias.");setGroups(payload.groups);}).catch((caught)=>{if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[]);
  function openGroup(group?:Group){setEditing({entity:"group",id:group?.id,systemCode:group?.systemCode});setName(group?.name??"");setNature(group?.nature??"DESPESA");setGroupId("");setIncludeInDrg(group?.includeInDrg??true);setActive(group?.active??true);setError("");}
  function openCategory(category?:Category,defaultGroupId?:string){setEditing({entity:"category",id:category?.id,systemCode:category?.systemCode});setName(category?.name??"");setNature(category?.nature??"DESPESA");setGroupId(category?.groupId??defaultGroupId??groups[0]?.id??"");setIncludeInDrg(category?.includeInDrg??true);setActive(category?.active??true);setError("");}
  async function save(event:FormEvent){event.preventDefault();if(!editing)return;setSaving(true);setError("");try{const response=await fetch(editing.id?`/api/financial-categories/${editing.id}`:"/api/financial-categories",{method:editing.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity:editing.entity,name,nature,groupId:editing.entity==="category"?groupId:undefined,includeInDrg,active})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível salvar.");await load();setEditing(undefined);setNotice(`${editing.entity==="group"?"Grupo":"Categoria"} ${editing.id?"atualizado":"cadastrado"}.`);}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível salvar.");}finally{setSaving(false);}}
  const categoryCount=groups.reduce((sum,group)=>sum+group.categories.length,0);
  return <div className="app-shell"><AppSidebar active="categorias_financeiras"/><main className="workspace registry-workspace">
    <header className="topbar registry-topbar"><button className="mobile-menu" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button><div><p className="eyebrow">CADASTROS FINANCEIROS</p><h1>Grupos e categorias</h1><p className="page-description">Organize as contas e escolha quais classificações compõem o DRG.</p></div><div className="header-button-group"><button className="secondary-button" onClick={()=>openGroup()}><Layers3 size={18}/>Novo grupo</button><button className="primary-button" onClick={()=>openCategory()}><Plus size={18}/>Nova categoria</button></div></header>
    {mobileMenu&&<div className="mobile-shortcuts registry-shortcuts"><Link href="/financeiro">Financeiro</Link><Link href="/categorias-financeiras">Categorias</Link><Link href="/fornecedores">Fornecedores</Link></div>}
    <section className="operations-stats"><div><Layers3/><span>Grupos</span><strong>{groups.length}</strong></div><div><Tags/><span>Categorias</span><strong>{categoryCount}</strong></div><div><CheckCircle2/><span>Incluídas no DRG</span><strong>{groups.reduce((sum,group)=>sum+group.categories.filter(category=>category.includeInDrg&&category.active).length,0)}</strong></div></section>
    {loading?<section className="registry-panel registry-loading"><LoaderCircle className="spin"/>Carregando categorias...</section>:<section className="financial-groups">{groups.map(group=><article className={`registry-panel financial-group ${!group.active?"inactive-row":""}`} key={group.id}><header><div><span className="section-kicker">{group.nature}</span><h2>{group.name}</h2><small>{group.includeInDrg?"Grupo incluído no DRG":"Grupo fora do DRG"}</small></div><div className="group-actions"><button className="table-action" onClick={()=>openGroup(group)}><Pencil size={15}/>Editar grupo</button><button className="table-action" onClick={()=>openCategory(undefined,group.id)}><Plus size={15}/>Categoria</button></div></header><div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>Subcategoria</th><th>Natureza</th><th>DRG</th><th>Status</th><th>Ações</th></tr></thead><tbody>{group.categories.map(category=><tr key={category.id} className={!category.active?"inactive-row":""}><td><strong>{category.name}</strong>{category.systemCode&&<small className="table-note">Categoria padrão do sistema</small>}</td><td>{category.nature}</td><td><span className={`registry-status ${category.includeInDrg?"active":"inactive"}`}>{category.includeInDrg?"Incluída":"Fora do DRG"}</span></td><td>{category.active?"Ativa":"Inativa"}</td><td><button className="table-action" onClick={()=>openCategory(category)}><Pencil size={15}/>Editar</button></td></tr>)}</tbody></table>{!group.categories.length&&<div className="empty-state">Nenhuma categoria neste grupo.</div>}</div></article>)}{!groups.length&&<div className="registry-panel empty-state">Nenhum grupo cadastrado.</div>}</section>}
    {error&&!editing&&<p className="platform-error">{error}</p>}
  </main>{editing&&<div className="modal-backdrop"><section className="registry-modal"><header className="modal-header"><div><span className="section-kicker">CLASSIFICAÇÃO</span><h2>{editing.id?"Editar":"Novo"} {editing.entity==="group"?"grupo":"categoria"}</h2></div><button className="icon-button" onClick={()=>setEditing(undefined)}><X/></button></header><form className="registry-form" onSubmit={save}><div className="form-grid registry-form-grid"><label className="field span-2"><span>Nome *</span><input value={name} onChange={event=>setName(event.target.value)} required autoFocus/></label>{editing.entity==="category"&&<label className="field span-2"><span>Grupo *</span><select value={groupId} onChange={event=>setGroupId(event.target.value)} required><option value="">Selecione</option>{groups.map(group=><option value={group.id} key={group.id}>{group.name}</option>)}</select></label>}<label className="field"><span>Natureza</span><select value={nature} onChange={event=>setNature(event.target.value as Nature)}><option value="DESPESA">Despesa</option><option value="RECEITA">Receita</option><option value="AMBOS">Ambos</option></select></label><label className="checkbox-field"><input type="checkbox" checked={includeInDrg} onChange={event=>setIncludeInDrg(event.target.checked)}/><span>Incluir no DRG</span></label>{editing.id&&<label className="checkbox-field"><input type="checkbox" checked={active} onChange={event=>setActive(event.target.checked)}/><span>Cadastro ativo</span></label>}</div>{editing.systemCode&&<p className="form-help">Esta classificação é usada nas automações do sistema. O nome e a exibição no DRG podem ser alterados sem romper o vínculo.</p>}{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?<LoaderCircle className="spin" size={18}/>:<CheckCircle2 size={18}/>}Salvar</button></footer></form></section></div>}{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}</div>;
}
