"use client";

import { AlertTriangle, ArrowUpFromLine, Boxes, ChartNoAxesColumnIncreasing, History, LoaderCircle, Menu, PackageX, Save, Search, SlidersHorizontal, TrendingUp, X } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";

type Health="SAUDAVEL"|"EMINENTE"|"RUPTURA"|"SEM_GIRO";
type Product={id:string;name:string;type?:string;costPrice:number;salePrice:number;stock:number;minimumStock:number;leadTimeDays:number;active:boolean;soldQuantity:number;orderCount:number;turnover:number|null;coverageDays:number|null;health:Health};
type Movement={id:string;productId?:string;productName?:string;date?:string;type?:string;quantity:number;partyName?:string;balance?:number};
type Summary={inventoryCostValue:number;inventorySaleValue:number;projectedMarginAmount:number;projectedMarginPercent:number;ruptures:number;imminent:number;noMovement:number};
type StockFilter="TODOS"|"POSITIVO"|"RUPTURA"|"EMINENTE"|"SEM_GIRO"|"INATIVO";
const currency=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});const number=new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2});const dateFormatter=new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"});
const today=()=>new Date().toLocaleDateString("en-CA");
const emptySummary:Summary={inventoryCostValue:0,inventorySaleValue:0,projectedMarginAmount:0,projectedMarginPercent:0,ruptures:0,imminent:0,noMovement:0};
const healthLabel:Record<Health,string>={SAUDAVEL:"Saudável",EMINENTE:"Risco de ruptura",RUPTURA:"Ruptura",SEM_GIRO:"Sem giro"};

export function InventoryPage(){
  const [products,setProducts]=useState<Product[]>([]);const [movements,setMovements]=useState<Movement[]>([]);const [summary,setSummary]=useState<Summary>(emptySummary);const [analysisDays,setAnalysisDays]=useState(90);
  const [loading,setLoading]=useState(true);const [query,setQuery]=useState("");const [filter,setFilter]=useState<StockFilter>("TODOS");const [tab,setTab]=useState<"SALDOS"|"MOVIMENTOS">("SALDOS");
  const [showAdjustment,setShowAdjustment]=useState(false);const [productId,setProductId]=useState("");const [type,setType]=useState<"ENTRADA"|"SAIDA"|"AJUSTE">("ENTRADA");const [quantity,setQuantity]=useState("");const [date,setDate]=useState(today);const [partyName,setPartyName]=useState("");
  const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [mobileMenu,setMobileMenu]=useState(false);
  function applyPayload(payload:{products:Product[];movements:Movement[];summary?:Summary;periodDays?:number}){setProducts(payload.products);setMovements(payload.movements);setSummary(payload.summary??emptySummary);if(payload.periodDays)setAnalysisDays(payload.periodDays);}
  useEffect(()=>{const controller=new AbortController();fetch("/api/inventory?days=90",{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível carregar o estoque.");applyPayload(payload);}).catch(caught=>{if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[]);
  async function load(days=analysisDays){setLoading(true);setError("");try{const response=await fetch(`/api/inventory?days=${days}`);const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível atualizar a análise.");applyPayload(payload);}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível atualizar a análise.");}finally{setLoading(false);}}
  const filtered=useMemo(()=>products.filter(product=>{const text=`${product.name} ${product.type??""}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"));const state=filter==="TODOS"||(filter==="POSITIVO"&&product.active&&product.stock>0)||(filter==="INATIVO"&&!product.active)||(filter!=="POSITIVO"&&filter!=="INATIVO"&&product.health===filter);return text&&state;}),[filter,products,query]);
  const activeProducts=products.filter(product=>product.active);const selectedProduct=products.find(product=>product.id===productId);const topProducts=[...activeProducts].filter(product=>product.soldQuantity>0).sort((a,b)=>b.soldQuantity-a.soldQuantity).slice(0,6);const maxSold=Math.max(1,...topProducts.map(product=>product.soldQuantity));
  function openAdjustment(product?:Product){setProductId(product?.id??"");setType("ENTRADA");setQuantity("");setDate(today());setPartyName("");setError("");setShowAdjustment(true);}
  async function saveAdjustment(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId,type,quantity:Number(quantity.replace(",",".")),date,partyName})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível movimentar o estoque.");await load();setShowAdjustment(false);setNotice(`${selectedProduct?.name??"Produto"}: novo saldo de ${number.format(payload.product.stock)}.`);}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível movimentar o estoque.");}finally{setSaving(false);}}
  return <div className="app-shell"><AppSidebar active="estoque"/><main className="workspace registry-workspace"><header className="topbar registry-topbar"><button className="mobile-menu" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Abrir menu"><Menu/></button><div><p className="eyebrow">INVENTÁRIO</p><h1>Gestão de estoque</h1><p className="page-description">Giro por vendas, cobertura, ruptura e valor potencial do estoque.</p></div><button className="primary-button" onClick={()=>openAdjustment()}><SlidersHorizontal size={18}/>Movimentar estoque</button></header>
    {mobileMenu&&<div className="mobile-shortcuts registry-shortcuts"><Link href="/compras">Compras</Link><Link href="/estoque">Estoque</Link><Link href="/produtos">Produtos</Link></div>}
    <section className="operations-stats inventory-stats"><div><Boxes/><span>Estoque a custo</span><strong>{currency.format(summary.inventoryCostValue)}</strong></div><div><TrendingUp/><span>Estoque a venda</span><strong>{currency.format(summary.inventorySaleValue)}</strong></div><div><ChartNoAxesColumnIncreasing/><span>Margem potencial</span><strong>{currency.format(summary.projectedMarginAmount)} <small>{number.format(summary.projectedMarginPercent)}%</small></strong></div><div><PackageX/><span>Ruptura / risco</span><strong>{summary.ruptures} / {summary.imminent}</strong></div></section>
    <section className="inventory-analysis-grid"><article className="registry-panel stock-health-card"><header><div><span className="section-kicker">SAÚDE DO ESTOQUE</span><h2>Alertas de reposição</h2></div></header><div><span className="stock-health rupture"><AlertTriangle/>Ruptura<strong>{summary.ruptures}</strong></span><span className="stock-health imminent"><History/>Risco de ruptura<strong>{summary.imminent}</strong></span><span className="stock-health no-turn"><Boxes/>Sem giro no período<strong>{summary.noMovement}</strong></span></div></article><article className="registry-panel top-products"><header><div><span className="section-kicker">MAIOR MOVIMENTAÇÃO</span><h2>Produtos mais vendidos</h2></div><span>Últimos {analysisDays} dias</span></header><div>{topProducts.map(product=><div className="top-product-row" key={product.id}><span title={product.name}>{product.name}</span><i><em style={{width:`${product.soldQuantity/maxSold*100}%`}}/></i><b>{number.format(product.soldQuantity)}</b></div>)}{!topProducts.length&&<p className="empty-compact">Nenhuma venda de produto no período.</p>}</div></article></section>
    <section className="inventory-toolbar"><div className="inventory-tabs"><button className={tab==="SALDOS"?"active":""} onClick={()=>setTab("SALDOS")}>Análise e saldos</button><button className={tab==="MOVIMENTOS"?"active":""} onClick={()=>setTab("MOVIMENTOS")}>Movimentações</button></div>{tab==="SALDOS"&&<><label className="compact-search"><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar produto"/></label><select value={filter} onChange={event=>setFilter(event.target.value as StockFilter)}><option value="TODOS">Todos</option><option value="POSITIVO">Com estoque</option><option value="RUPTURA">Em ruptura</option><option value="EMINENTE">Risco de ruptura</option><option value="SEM_GIRO">Sem giro</option><option value="INATIVO">Inativos</option></select><select value={analysisDays} onChange={event=>{const days=Number(event.target.value);setAnalysisDays(days);void load(days);}} aria-label="Período da análise"><option value="30">30 dias</option><option value="60">60 dias</option><option value="90">90 dias</option><option value="180">180 dias</option><option value="365">365 dias</option></select></>}</section>
    <section className="registry-panel">{loading?<div className="registry-loading"><LoaderCircle className="spin"/>Calculando indicadores...</div>:error&&!products.length?<div className="empty-state">{error}</div>:tab==="SALDOS"?<div className="registry-table-wrap"><table className="registry-table inventory-analysis-table"><thead><tr><th>Produto</th><th>Saldo / mínimo</th><th>Vendas</th><th>Pedidos</th><th>Giro</th><th>Cobertura</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{filtered.map(product=><tr key={product.id} className={!product.active?"inactive-row":product.health==="RUPTURA"||product.health==="EMINENTE"?"stock-alert-row":""}><td data-label="Produto"><strong>{product.name}</strong><small className="table-note">Custo {currency.format(product.costPrice)} · venda {currency.format(product.salePrice)}</small></td><td data-label="Saldo / mínimo"><strong>{number.format(product.stock)}</strong><small className="table-note">mín. {number.format(product.minimumStock)}</small></td><td data-label="Vendas">{number.format(product.soldQuantity)}</td><td data-label="Pedidos">{product.orderCount}</td><td data-label="Giro">{product.turnover===null?"—":`${number.format(product.turnover)}x`}</td><td data-label="Cobertura">{product.coverageDays===null?"Sem consumo":`${number.format(product.coverageDays)} dias`}</td><td data-label="Situação"><span className={`stock-health-badge ${product.health.toLowerCase()}`}>{healthLabel[product.health]}</span></td><td data-label="Ações"><button className="table-action" onClick={()=>openAdjustment(product)}><SlidersHorizontal size={16}/>Movimentar</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state">Nenhum produto encontrado.</div>}</div>:<div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>Data</th><th>Produto</th><th>Movimento</th><th>Origem/destino</th><th>Quantidade</th><th>Saldo após</th></tr></thead><tbody>{movements.map(movement=><tr key={movement.id}><td data-label="Data">{movement.date?dateFormatter.format(new Date(`${movement.date}T00:00:00Z`)):"—"}</td><td data-label="Produto"><strong>{movement.productName??"Produto não localizado"}</strong></td><td data-label="Movimento"><span className={`movement-badge ${String(movement.type).includes("SAIDA")||movement.type==="VENDA"?"out":"in"}`}>{movement.type??"—"}</span></td><td data-label="Origem/destino">{movement.partyName??"—"}</td><td data-label="Quantidade">{number.format(movement.quantity)}</td><td data-label="Saldo após">{movement.balance===undefined||movement.balance===null?"—":number.format(movement.balance)}</td></tr>)}</tbody></table>{!movements.length&&<div className="empty-state">Nenhuma movimentação encontrada.</div>}</div>}</section>
  </main>{showAdjustment&&<div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setShowAdjustment(false)}><section className="registry-modal"><header className="modal-header"><div><span className="section-kicker">INVENTÁRIO</span><h2>Movimentar estoque</h2></div><button className="icon-button" onClick={()=>setShowAdjustment(false)}><X/></button></header><form className="registry-form" onSubmit={saveAdjustment}><div className="form-grid registry-form-grid"><label className="field span-2"><span>Produto *</span><select value={productId} onChange={event=>setProductId(event.target.value)} required><option value="">Selecione</option>{activeProducts.map(product=><option key={product.id} value={product.id}>{product.name} — saldo {number.format(product.stock)}</option>)}</select></label><label className="field"><span>Tipo *</span><select value={type} onChange={event=>setType(event.target.value as typeof type)}><option value="ENTRADA">Entrada</option><option value="SAIDA">Saída</option><option value="AJUSTE">Definir saldo exato</option></select></label><label className="field"><span>{type==="AJUSTE"?"Novo saldo":"Quantidade"} *</span><input type="number" min="0" step="0.001" value={quantity} onChange={event=>setQuantity(event.target.value)} required/></label><label className="field"><span>Data</span><input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label className="field"><span>Origem/destino</span><input value={partyName} onChange={event=>setPartyName(event.target.value)} placeholder="Fornecedor, cliente ou motivo"/></label></div>{selectedProduct&&<p className="current-balance">Saldo atual de <strong>{selectedProduct.name}</strong>: {number.format(selectedProduct.stock)}</p>}{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setShowAdjustment(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?<LoaderCircle className="spin" size={18}/>:type==="SAIDA"?<ArrowUpFromLine size={18}/>:<Save size={18}/>}Confirmar movimentação</button></footer></form></section></div>}{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}</div>;
}
