"use client";

import { AlertTriangle, ArrowLeft, BadgeCheck, Database, FileSpreadsheet, LoaderCircle, Menu, RefreshCw, Rows3, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";

type Comparison={code:string;label:string;valueLabel:string|null;coreCount:number;liveCount:number;missingCount:number;coreValue:number;liveValue:number};
type Incomplete={code:string;label:string;count:number;samples:string[]};
type Payload={applicable:boolean;checkedAt:string;message?:string;comparisons?:Comparison[];incomplete?:Incomplete[];rawTables?:Array<{name:string;rows:number}>;summary?:{datasets:number;migrated:number;missing:number;incomplete:number;valueDifferences:number;rawRows:number}};
const integer=new Intl.NumberFormat("pt-BR");const decimal=new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2});const dateTime=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"});

export function MigrationReconciliationPage(){
  const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [mobileMenu,setMobileMenu]=useState(false);
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{const response=await fetch("/api/migration-reconciliation",{signal});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível conferir a migração.");setData(payload);}catch(caught){if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{const controller=new AbortController();fetch("/api/migration-reconciliation",{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível conferir a migração.");setData(payload);}).catch(caught=>{if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[]);
  const healthy=Boolean(data?.summary&&!data.summary.missing&&!data.summary.valueDifferences);
  return <div className="app-shell"><AppSidebar active="conferencia"/><main className="workspace registry-workspace"><header className="topbar registry-topbar"><button className="mobile-menu" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Abrir menu"><Menu/></button><div><p className="eyebrow">MIGRAÇÃO HISTÓRICA</p><h1>Reconciliação do AppSheet</h1><p className="page-description">Compare as fontes importadas com o banco utilizado pelo novo sistema.</p></div><div className="topbar-actions"><Link className="secondary-button" href="/conferencia"><ArrowLeft size={18}/>Integridade operacional</Link><button className="primary-button" disabled={loading} onClick={()=>load()}>{loading?<LoaderCircle className="spin" size={18}/>:<RefreshCw size={18}/>}Conferir novamente</button></div></header>{mobileMenu&&<div className="mobile-shortcuts registry-shortcuts"><Link href="/conferencia">Integridade</Link><Link href="/conferencia/pagamentos">Recebimentos</Link></div>}
    {loading&&!data?<div className="registry-panel registry-loading"><LoaderCircle className="spin"/>Comparando a planilha e o PostgreSQL...</div>:error?<div className="registry-panel empty-state">{error}</div>:data&&!data.applicable?<section className="migration-not-applicable"><Database/><h2>Sem migração histórica</h2><p>{data.message}</p><Link className="secondary-button" href="/conferencia">Voltar para a conferência operacional</Link></section>:data?.summary&&<><section className="operations-stats migration-stats"><div><FileSpreadsheet/><span>Linhas na origem bruta</span><strong>{integer.format(data.summary.rawRows)}</strong></div><div><Database/><span>Registros migrados</span><strong>{integer.format(data.summary.migrated)}</strong></div><div className={data.summary.missing?"danger":""}><AlertTriangle/><span>Não migrados</span><strong>{integer.format(data.summary.missing)}</strong></div><div className={data.summary.incomplete?"warning":""}><Rows3/><span>Cadastros incompletos</span><strong>{integer.format(data.summary.incomplete)}</strong></div></section>
      <section className={`migration-verdict ${healthy?"healthy":"attention"}`}>{healthy?<BadgeCheck/>:<AlertTriangle/>}<div><strong>{healthy?"Todas as chaves históricas foram migradas.":"A migração possui pontos que precisam de conferência."}</strong><span>{healthy?"As contagens e os totais conciliáveis do modelo tratado conferem com o banco operacional.":"Consulte os conjuntos e pendências abaixo. Nenhum dado foi alterado por esta análise."}</span></div><small>Verificado em {dateTime.format(new Date(data.checkedAt))}</small></section>
      <section className="migration-grid"><article className="registry-panel migration-comparison"><header><span className="section-kicker">APP_CORE → APP_LIVE</span><h2>Conferência por conjunto</h2></header><div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>Conjunto</th><th>Tratados</th><th>Migrados</th><th>Faltantes</th><th>Conciliação</th></tr></thead><tbody>{data.comparisons?.map(item=>{const valueDiff=Math.abs(item.coreValue-item.liveValue);const ok=!item.missingCount&&(!item.valueLabel||valueDiff<=.01);return <tr key={item.code}><td data-label="Conjunto"><strong>{item.label}</strong>{item.valueLabel&&<small className="table-note">{item.valueLabel}: {decimal.format(item.coreValue)} → {decimal.format(item.liveValue)}</small>}</td><td data-label="Tratados">{integer.format(item.coreCount)}</td><td data-label="Migrados">{integer.format(item.liveCount)}</td><td data-label="Faltantes">{integer.format(item.missingCount)}</td><td data-label="Conciliação"><span className={`registry-status ${ok?"active":"inactive"}`}>{ok?"Confere":"Revisar"}</span></td></tr>;})}</tbody></table></div></article>
        <article className="registry-panel migration-incomplete"><header><span className="section-kicker">QUALIDADE DOS DADOS</span><h2>Registros incompletos</h2></header>{data.incomplete?.map(item=><details key={item.code} className={item.count?"has-items":"clean"}><summary><span>{item.count?<AlertTriangle/>:<ShieldCheck/>}<b>{item.label}</b></span><strong>{integer.format(item.count)}</strong></summary>{item.count>0&&<div>{item.samples.length?<>{item.samples.map((sample,index)=><p key={`${sample}-${index}`}>{sample}</p>)}{item.count>item.samples.length&&<small>e mais {integer.format(item.count-item.samples.length)} registro(s)</small>}</>:<p>Há registros para revisar.</p>}</div>}</details>)}</article>
      </section>
      <details className="registry-panel raw-tables"><summary><span><FileSpreadsheet/>Tabelas preservadas da planilha original</span><strong>{data.rawTables?.length??0} tabela(s)</strong></summary><div>{data.rawTables?.map(table=><span key={table.name}><b>{table.name}</b>{integer.format(table.rows)} linha(s)</span>)}</div></details>
    </>}
  </main></div>;
}
