"use client";

import { AlertTriangle, BadgeCheck, CalendarClock, CircleDollarSign, LoaderCircle, Menu, Plus, Search, WalletCards, X } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";

type Status = "PENDENTE" | "PARCIAL" | "VENCIDO" | "PAGO" | "CANCELADO";
type Payable = { id:string;supplierId?:string;supplierName?:string;description:string;documentNumber?:string;issueDate:string;competenceDate:string;dueDate:string;paymentDate?:string;originalAmount:number;openAmount:number;status:Status;installmentNumber:number;installmentCount:number;categoryName?:string;paymentMethod?:string;notes?:string };
type Option = { id:string;name:string };
type Category = Option & { groupName:string };
type Method = Option & { defaultAccountId?:string };
type Payload = { payables:Payable[];suppliers:Option[];categories:Category[];accounts:Option[];paymentMethods:Method[] };

const money = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" });
const formatDate = new Intl.DateTimeFormat("pt-BR", { timeZone:"UTC" });
const today = () => new Date().toLocaleDateString("en-CA");
const showDate = (value?:string) => value ? formatDate.format(new Date(`${value.slice(0,10)}T00:00:00Z`)) : "—";

export function PayablesPage() {
  const [data,setData] = useState<Payload>({ payables:[],suppliers:[],categories:[],accounts:[],paymentMethods:[] });
  const [loading,setLoading] = useState(true); const [saving,setSaving] = useState(false); const [error,setError] = useState(""); const [notice,setNotice] = useState("");
  const [query,setQuery] = useState(""); const [status,setStatus] = useState<Status|"TODOS">("TODOS"); const [mobileMenu,setMobileMenu] = useState(false);
  const [showCreate,setShowCreate] = useState(false); const [paying,setPaying] = useState<Payable>();
  const [supplierId,setSupplierId] = useState(""); const [categoryId,setCategoryId] = useState(""); const [description,setDescription] = useState(""); const [documentNumber,setDocumentNumber] = useState("");
  const [issueDate,setIssueDate] = useState(today); const [competenceDate,setCompetenceDate] = useState(today); const [dueDate,setDueDate] = useState(today); const [amount,setAmount] = useState(""); const [notes,setNotes] = useState("");
  const [paymentDate,setPaymentDate] = useState(today); const [paymentMethodId,setPaymentMethodId] = useState(""); const [financialAccountId,setFinancialAccountId] = useState("");
  const [interest,setInterest] = useState("0"); const [fine,setFine] = useState("0"); const [discount,setDiscount] = useState("0");

  async function load(signal?:AbortSignal) { const response=await fetch("/api/payables",{signal});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível carregar as contas.");setData(payload); }
  useEffect(()=>{const controller=new AbortController();fetch("/api/payables",{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível carregar as contas.");setData(payload);}).catch(caught=>{if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[]);

  const visible=useMemo(()=>data.payables.filter(item=>(status==="TODOS"||item.status===status)&&`${item.supplierName??""} ${item.description} ${item.documentNumber??""}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))),[data.payables,query,status]);
  const active=data.payables.filter(item=>item.status!=="CANCELADO"); const open=active.filter(item=>["PENDENTE","PARCIAL","VENCIDO"].includes(item.status)); const overdue=active.filter(item=>item.status==="VENCIDO"); const paid=active.filter(item=>item.status==="PAGO");
  const dueToday=open.filter(item=>item.dueDate.slice(0,10)===today()); const paymentTotal=Math.max(0,(paying?.openAmount??0)+(Number(interest.replace(",","."))||0)+(Number(fine.replace(",","."))||0)-(Number(discount.replace(",","."))||0));

  function resetCreate(){setSupplierId("");setCategoryId("");setDescription("");setDocumentNumber("");setIssueDate(today());setCompetenceDate(today());setDueDate(today());setAmount("");setNotes("");setError("");}
  async function create(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/payables",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierId:supplierId||undefined,categoryId,description,documentNumber,issueDate,competenceDate,dueDate,amount:Number(amount.replace(",",".")),notes})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível salvar.");await load();setShowCreate(false);setNotice("Conta a pagar registrada e reconhecida na competência informada.");}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível salvar.");}finally{setSaving(false);}}
  function openPayment(item:Payable){const method=data.paymentMethods[0];setPaying(item);setPaymentDate(today());setPaymentMethodId(method?.id??"");setFinancialAccountId(method?.defaultAccountId??data.accounts[0]?.id??"");setInterest("0");setFine("0");setDiscount("0");setError("");}
  async function change(item:Payable,action:"PAY"|"REOPEN"){setSaving(true);setError("");try{const response=await fetch(`/api/payables/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,paymentDate,paymentMethodId,financialAccountId,interestAmount:Number(interest.replace(",",".")),fineAmount:Number(fine.replace(",",".")),discountAmount:Number(discount.replace(",","."))})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível atualizar.");await load();setPaying(undefined);setNotice(action==="PAY"?"Pagamento confirmado e lançado na conta financeira.":"Pagamento estornado e conta reaberta.");}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível atualizar.");}finally{setSaving(false);}}

  return <div className="app-shell"><AppSidebar active="pagar"/><main className="workspace registry-workspace"><header className="topbar registry-topbar"><button className="mobile-menu" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Abrir menu"><Menu/></button><div><p className="eyebrow">FINANCEIRO</p><h1>Contas a pagar</h1><p className="page-description">Obrigações por vencimento, competência e conta financeira.</p></div><button className="primary-button" onClick={()=>{resetCreate();setShowCreate(true);}}><Plus size={18}/>Nova conta</button></header>
    {mobileMenu&&<div className="mobile-shortcuts registry-shortcuts"><Link href="/receber">Contas a receber</Link><Link href="/pagar">Contas a pagar</Link><Link href="/financeiro">Financeiro</Link></div>}
    <section className="operations-stats finance-stats"><div><CircleDollarSign/><span>Em aberto</span><strong>{money.format(open.reduce((sum,item)=>sum+item.openAmount,0))}</strong></div><div><AlertTriangle/><span>Vencido</span><strong>{money.format(overdue.reduce((sum,item)=>sum+item.openAmount,0))}</strong></div><div><CalendarClock/><span>Vence hoje</span><strong>{money.format(dueToday.reduce((sum,item)=>sum+item.openAmount,0))}</strong></div><div><BadgeCheck/><span>Pago</span><strong>{money.format(paid.reduce((sum,item)=>sum+item.originalAmount,0))}</strong></div></section>
    <section className="financial-toolbar"><label className="compact-search"><Search size={18}/><input placeholder="Fornecedor, descrição ou documento" value={query} onChange={event=>setQuery(event.target.value)}/></label><select value={status} onChange={event=>setStatus(event.target.value as Status|"TODOS")}><option value="TODOS">Todos os status</option><option value="PENDENTE">Pendentes</option><option value="PARCIAL">Parciais</option><option value="VENCIDO">Vencidos</option><option value="PAGO">Pagos</option><option value="CANCELADO">Cancelados</option></select></section>
    <section className="registry-panel">{loading?<div className="registry-loading"><LoaderCircle className="spin"/>Carregando...</div>:error&&!data.payables.length?<div className="empty-state">{error}</div>:<div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>Fornecedor / descrição</th><th>Competência</th><th>Vencimento</th><th>Pagamento</th><th>Categoria</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td data-label="Conta"><strong>{item.supplierName||item.description}</strong>{item.supplierName&&<small className="table-note">{item.description}</small>}{item.documentNumber&&<small className="table-note">Documento: {item.documentNumber}</small>}</td><td data-label="Competência">{showDate(item.competenceDate)}</td><td data-label="Vencimento">{showDate(item.dueDate)}</td><td data-label="Pagamento">{showDate(item.paymentDate)}</td><td data-label="Categoria">{item.categoryName||"—"}</td><td data-label="Valor"><strong>{money.format(item.originalAmount)}</strong>{item.openAmount!==item.originalAmount&&<small className="table-note">Aberto: {money.format(item.openAmount)}</small>}</td><td data-label="Status"><span className={`financial-status ${item.status.toLowerCase()}`}>{item.status}</span></td><td data-label="Ações">{["PENDENTE","PARCIAL","VENCIDO"].includes(item.status)?<button className="table-action" onClick={()=>openPayment(item)}><BadgeCheck size={16}/>Pagar</button>:item.status==="PAGO"?<button className="table-action" disabled={saving} onClick={()=>void change(item,"REOPEN")}>Reabrir</button>:"—"}</td></tr>)}</tbody></table>{!visible.length&&<div className="empty-state">Nenhuma conta encontrada.</div>}</div>}</section>
  </main>
  {showCreate&&<div className="modal-backdrop"><section className="registry-modal"><header className="modal-header"><div><span className="section-kicker">OBRIGAÇÃO</span><h2>Nova conta a pagar</h2></div><button className="icon-button" onClick={()=>setShowCreate(false)}><X/></button></header><form className="registry-form" onSubmit={create}><div className="form-grid registry-form-grid"><label className="field"><span>Fornecedor</span><select value={supplierId} onChange={event=>setSupplierId(event.target.value)}><option value="">Sem fornecedor vinculado</option>{data.suppliers.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Categoria *</span><select value={categoryId} onChange={event=>setCategoryId(event.target.value)} required><option value="">Selecione</option>{data.categories.map(item=><option value={item.id} key={item.id}>{item.groupName} · {item.name}</option>)}</select></label><label className="field span-2"><span>Descrição *</span><input value={description} onChange={event=>setDescription(event.target.value)} required/></label><label className="field"><span>Documento</span><input value={documentNumber} onChange={event=>setDocumentNumber(event.target.value)}/></label><label className="field"><span>Valor *</span><input type="number" min="0.01" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} required/></label><label className="field"><span>Emissão *</span><input type="date" value={issueDate} onChange={event=>setIssueDate(event.target.value)} required/></label><label className="field"><span>Competência *</span><input type="date" value={competenceDate} onChange={event=>setCompetenceDate(event.target.value)} required/></label><label className="field"><span>Vencimento *</span><input type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)} required/></label><label className="field"><span>Observações</span><input value={notes} onChange={event=>setNotes(event.target.value)}/></label></div>{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setShowCreate(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?<LoaderCircle className="spin" size={18}/>:<Plus size={18}/>}Salvar conta</button></footer></form></section></div>}
  {paying&&<div className="modal-backdrop"><section className="registry-modal compact-modal"><header className="modal-header"><div><span className="section-kicker">BAIXA</span><h2>Confirmar pagamento</h2></div><button className="icon-button" onClick={()=>setPaying(undefined)}><X/></button></header><form className="registry-form" onSubmit={event=>{event.preventDefault();void change(paying,"PAY");}}><p className="payment-callout"><WalletCards/><span><b>{paying.description}</b><br/>{money.format(paying.openAmount)} em aberto</span></p><div className="form-grid registry-form-grid"><label className="field"><span>Data do pagamento</span><input type="date" value={paymentDate} onChange={event=>setPaymentDate(event.target.value)} required/></label><label className="field"><span>Forma de pagamento</span><select value={paymentMethodId} onChange={event=>{const method=data.paymentMethods.find(item=>item.id===event.target.value);setPaymentMethodId(event.target.value);if(method?.defaultAccountId)setFinancialAccountId(method.defaultAccountId);}} required><option value="">Selecione</option>{data.paymentMethods.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field span-2"><span>Conta financeira</span><select value={financialAccountId} onChange={event=>setFinancialAccountId(event.target.value)} required><option value="">Selecione</option>{data.accounts.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Juros</span><input type="number" min="0" step="0.01" value={interest} onChange={event=>setInterest(event.target.value)}/></label><label className="field"><span>Multa</span><input type="number" min="0" step="0.01" value={fine} onChange={event=>setFine(event.target.value)}/></label><label className="field span-2"><span>Desconto</span><input type="number" min="0" step="0.01" value={discount} onChange={event=>setDiscount(event.target.value)}/></label></div><div className="payment-fee-summary"><span>Valor em aberto<b>{money.format(paying.openAmount)}</b></span><span>Acréscimos/desconto<b>{money.format(paymentTotal-paying.openAmount)}</b></span><span>Total a pagar<b>{money.format(paymentTotal)}</b></span></div>{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setPaying(undefined)}>Cancelar</button><button className="primary-button" disabled={saving}><BadgeCheck size={18}/>Confirmar pagamento</button></footer></form></section></div>}
  {notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}</div>;
}
