"use client";

import { AlertTriangle, ArrowLeft, BadgeCheck, CheckCircle2, CircleDashed, FlaskConical, LoaderCircle, Menu, RefreshCw, Rocket, Save, ShieldCheck, Users } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";

type Automatic={key:string;label:string;status:"OK"|"ATENCAO"|"ERRO";detail:string};
type Item={key:string;category:string;label:string;description:string;completed:boolean;notes:string|null;completed_at:string|null;completed_by_name:string|null};
type TestStatus="PENDENTE"|"APROVADO"|"REPROVADO"|"BLOQUEADO";
type Scenario={key:string;area:string;title:string;steps:string;status:TestStatus;notes:string|null;tested_at:string|null;tested_by_name:string|null};
type Payload={checkedAt:string;canEdit:boolean;automatic:Automatic[];items:Item[];scenarios:Scenario[];summary:{automaticReady:number;automaticTotal:number;completed:number;total:number;testsPassed:number;testsTotal:number;percentage:number;ready:boolean}};
const dateTime=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"});

export function ReadinessPage(){
  const [data,setData]=useState<Payload|null>(null);const [notes,setNotes]=useState<Record<string,string>>({});const [testNotes,setTestNotes]=useState<Record<string,string>>({});const [testStatuses,setTestStatuses]=useState<Record<string,TestStatus>>({});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [mobileMenu,setMobileMenu]=useState(false);
  const receive=useCallback((payload:Payload)=>{setData(payload);setNotes(Object.fromEntries(payload.items.map(item=>[item.key,item.notes??""])));setTestNotes(Object.fromEntries(payload.scenarios.map(item=>[item.key,item.notes??""])));setTestStatuses(Object.fromEntries(payload.scenarios.map(item=>[item.key,item.status])));},[]);
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{const response=await fetch("/api/readiness",{signal});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível avaliar a prontidão.");receive(payload);}catch(caught){if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}finally{setLoading(false);}},[receive]);
  useEffect(()=>{const controller=new AbortController();fetch("/api/readiness",{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível avaliar a prontidão.");receive(payload);}).catch(caught=>{if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[receive]);
  const groups=useMemo(()=>Object.entries((data?.items??[]).reduce<Record<string,Item[]>>((result,item)=>{(result[item.category]??=[]).push(item);return result;},{})),[data]);
  async function update(item:Item,completed=item.completed){setSaving(item.key);setError("");try{const response=await fetch("/api/readiness",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:item.key,completed,notes:notes[item.key]??""})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível atualizar o item.");await load();setNotice(completed?"Etapa marcada como concluída.":"Etapa reaberta no checklist.");}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível atualizar o item.");}finally{setSaving("");}}
  async function saveScenario(item:Scenario){setSaving(`test:${item.key}`);setError("");try{const response=await fetch("/api/readiness/tests",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:item.key,status:testStatuses[item.key]??"PENDENTE",notes:testNotes[item.key]??""})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível registrar o teste.");await load();setNotice("Resultado da homologação registrado.");}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível registrar o teste.");}finally{setSaving("");}}
  return <div className="app-shell"><AppSidebar active="conferencia"/><main className="workspace registry-workspace"><header className="topbar registry-topbar"><button className="mobile-menu" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Abrir menu"><Menu/></button><div><p className="eyebrow">ENTRADA EM PRODUÇÃO</p><h1>Central de prontidão</h1><p className="page-description">Acompanhe os requisitos técnicos e operacionais antes de substituir definitivamente o AppSheet.</p></div><div className="topbar-actions"><Link className="secondary-button" href="/conferencia"><ArrowLeft size={18}/>Integridade</Link><button className="primary-button" disabled={loading} onClick={()=>load()}>{loading?<LoaderCircle className="spin" size={18}/>:<RefreshCw size={18}/>}Atualizar diagnóstico</button></div></header>{mobileMenu&&<div className="mobile-shortcuts registry-shortcuts"><Link href="/conferencia">Integridade</Link><Link href="/conferencia/migracao">Migração</Link></div>}
    <section className="operations-stats readiness-stats"><div><ShieldCheck/><span>Verificações automáticas</span><strong>{data?`${data.summary.automaticReady}/${data.summary.automaticTotal}`:"—"}</strong></div><div><FlaskConical/><span>Cenários aprovados</span><strong>{data?`${data.summary.testsPassed}/${data.summary.testsTotal}`:"—"}</strong></div><div><CheckCircle2/><span>Checklist concluído</span><strong>{data?`${data.summary.completed}/${data.summary.total}`:"—"}</strong></div><div><Rocket/><span>Progresso da implantação</span><strong>{data?`${data.summary.percentage}%`:"—"}</strong></div><div className={data?.summary.ready?"ready":"warning"}><Users/><span>Situação</span><strong>{data?.summary.ready?"Pronto":"Em preparação"}</strong></div></section>
    {error&&<p className="form-error readiness-error">{error}</p>}{loading&&!data?<div className="registry-panel registry-loading"><LoaderCircle className="spin"/>Avaliando ambiente...</div>:data&&<><section className={`readiness-verdict ${data.summary.ready?"ready":"pending"}`}>{data.summary.ready?<Rocket/>:<CircleDashed/>}<div><strong>{data.summary.ready?"A empresa está pronta para o corte definitivo.":"Ainda existem etapas antes do corte definitivo."}</strong><span>{data.summary.ready?"Todos os requisitos automáticos e manuais foram concluídos.":"Finalize o checklist e resolva os alertas automáticos antes de deixar o AppSheet somente para consulta."}</span></div><small>Verificado em {dateTime.format(new Date(data.checkedAt))}</small></section>
      <section className="registry-panel readiness-tests"><header><div><span className="section-kicker">HOMOLOGAÇÃO ASSISTIDA</span><h2>Cenários obrigatórios</h2></div><strong>{data.summary.testsPassed}/{data.summary.testsTotal} aprovados</strong></header><p className="readiness-tests-intro">Execute cada roteiro com dados de teste e registre o resultado. Aprovações e reprovações exigem uma evidência ou observação.</p><div className="readiness-test-grid">{data.scenarios.map(item=><article key={item.key} className={`test-${item.status.toLocaleLowerCase("pt-BR")}`}><div className="readiness-test-heading"><span>{item.area}</span><strong>{item.title}</strong></div><p>{item.steps}</p>{item.tested_at&&<small>Última execução em {dateTime.format(new Date(item.tested_at))}{item.tested_by_name?` por ${item.tested_by_name}`:""}</small>}<div className="readiness-test-fields"><select disabled={!data.canEdit} value={testStatuses[item.key]??item.status} onChange={event=>setTestStatuses(current=>({...current,[item.key]:event.target.value as TestStatus}))}><option value="PENDENTE">Pendente</option><option value="APROVADO">Aprovado</option><option value="REPROVADO">Reprovado</option><option value="BLOQUEADO">Bloqueado</option></select><textarea disabled={!data.canEdit} placeholder="Evidência, resultado encontrado ou motivo do bloqueio..." value={testNotes[item.key]??""} onChange={event=>setTestNotes(current=>({...current,[item.key]:event.target.value}))}/>{data.canEdit&&((testStatuses[item.key]??item.status)!==item.status||(testNotes[item.key]??"")!==(item.notes??""))&&<button className="secondary-button" disabled={saving===`test:${item.key}`} onClick={()=>saveScenario(item)}>{saving===`test:${item.key}`?<LoaderCircle className="spin" size={15}/>:<Save size={15}/>}Salvar resultado</button>}</div></article>)}</div></section>
      <section className="readiness-layout"><article className="registry-panel readiness-automatic"><header><span className="section-kicker">DIAGNÓSTICO AUTOMÁTICO</span><h2>Ambiente e dados</h2></header>{data.automatic.map(item=><div key={item.key} className={item.status.toLocaleLowerCase("pt-BR")}><span>{item.status==="OK"?<BadgeCheck/>:<AlertTriangle/>}<b>{item.label}</b></span><small>{item.detail}</small><strong>{item.status==="OK"?"Pronto":item.status==="ERRO"?"Corrigir":"Revisar"}</strong></div>)}</article>
        <div className="readiness-checklist">{groups.map(([category,items])=><section className="registry-panel" key={category}><header><span className="section-kicker">{category}</span><strong>{items.filter(item=>item.completed).length}/{items.length}</strong></header>{items.map(item=><article key={item.key} className={item.completed?"completed":""}><button className="readiness-toggle" disabled={!data.canEdit||saving===item.key} onClick={()=>update(item,!item.completed)} aria-label={item.completed?"Reabrir etapa":"Concluir etapa"}>{saving===item.key?<LoaderCircle className="spin"/>:item.completed?<CheckCircle2/>:<CircleDashed/>}</button><div><h3>{item.label}</h3><p>{item.description}</p>{item.completed&&item.completed_at&&<small>Concluído em {dateTime.format(new Date(item.completed_at))}{item.completed_by_name?` por ${item.completed_by_name}`:""}</small>}<textarea disabled={!data.canEdit} placeholder="Observações, responsável ou evidência..." value={notes[item.key]??""} onChange={event=>setNotes(current=>({...current,[item.key]:event.target.value}))}/>{data.canEdit&&notes[item.key]!==item.notes&&<button className="text-button readiness-save" disabled={saving===item.key} onClick={()=>update(item)}><Save size={14}/>Salvar observação</button>}</div></article>)}</section>)}</div>
      </section></>}{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}
  </main></div>;
}
