"use client";

import { AlertTriangle, BadgeCheck, Boxes, ChevronRight, CircleDollarSign, ClipboardCheck, Database, LoaderCircle, Menu, RefreshCw, Rocket, Search, ShieldAlert, ShoppingCart } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";

type Module = "VENDAS" | "ESTOQUE" | "COMPRAS" | "FINANCEIRO";
type Issue = { id:string;code:string;module:Module;severity:"CRITICO"|"ALERTA";title:string;reference:string;description:string;expected:number;actual:number };
type Check = { code:string;module:Module;title:string;issueCount:number;status:"OK"|"DIVERGENTE" };
type Payload = { checkedAt:string;issues:Issue[];checks:Check[];summary:{checks:number;passed:number;total:number;critical:number;warnings:number} };
const number=new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2});
const dateTime=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"});
const moduleLabels:Record<Module,string>={VENDAS:"Vendas",ESTOQUE:"Estoque",COMPRAS:"Compras",FINANCEIRO:"Financeiro"};
const moduleLinks:Record<Module,string>={VENDAS:"/orcamentos",ESTOQUE:"/estoque",COMPRAS:"/compras",FINANCEIRO:"/financeiro"};

export function ReconciliationPage(){
  const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [mobileMenu,setMobileMenu]=useState(false);
  const [search,setSearch]=useState("");const [module,setModule]=useState<Module|"TODOS">("TODOS");const [severity,setSeverity]=useState<"TODOS"|"CRITICO"|"ALERTA">("TODOS");
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{const response=await fetch("/api/reconciliation",{signal});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível executar a conferência.");setData(payload);}catch(caught){if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{const controller=new AbortController();fetch("/api/reconciliation",{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível executar a conferência.");setData(payload);}).catch(caught=>{if(caught instanceof Error&&caught.name!=="AbortError")setError(caught.message);}).finally(()=>setLoading(false));return()=>controller.abort();},[]);
  const issues=useMemo(()=>data?.issues.filter(issue=>(module==="TODOS"||issue.module===module)&&(severity==="TODOS"||issue.severity===severity)&&`${issue.title} ${issue.reference} ${issue.description}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")))??[],[data,module,severity,search]);
  return <div className="app-shell"><AppSidebar active="conferencia"/><main className="workspace registry-workspace"><header className="topbar registry-topbar"><button className="mobile-menu" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Abrir menu"><Menu/></button><div><p className="eyebrow">CONTROLE OPERACIONAL</p><h1>Conferência e integridade</h1><p className="page-description">Cruze vendas, compras, estoque e financeiro antes que uma divergência vire um saldo incorreto.</p></div><div className="topbar-actions"><Link className="secondary-button" href="/conferencia/prontidao"><Rocket size={18}/>Prontidão</Link><Link className="secondary-button" href="/conferencia/migracao"><Database size={18}/>Migração histórica</Link><Link className="secondary-button" href="/conferencia/pagamentos"><ClipboardCheck size={18}/>Conferir recebimentos</Link><button className="primary-button" disabled={loading} onClick={()=>load()}>{loading?<LoaderCircle className="spin" size={18}/>:<RefreshCw size={18}/>}Executar novamente</button></div></header>{mobileMenu&&<div className="mobile-shortcuts registry-shortcuts"><Link href="/">Atendimento</Link><Link href="/conferencia/prontidao">Prontidão</Link><Link href="/conferencia/migracao">Migração</Link><Link href="/conferencia/pagamentos">Recebimentos</Link></div>}
    <section className="operations-stats reconciliation-stats"><div><BadgeCheck/><span>Verificações aprovadas</span><strong>{data?`${data.summary.passed}/${data.summary.checks}`:"—"}</strong></div><div className={data?.summary.critical?"danger":""}><ShieldAlert/><span>Divergências críticas</span><strong>{data?.summary.critical??0}</strong></div><div className={data?.summary.warnings?"warning":""}><AlertTriangle/><span>Alertas</span><strong>{data?.summary.warnings??0}</strong></div><div><CircleDollarSign/><span>Total de ocorrências</span><strong>{data?.summary.total??0}</strong></div></section>
    {data&&<section className={`reconciliation-banner ${data.summary.total?"has-issues":"healthy"}`}>{data.summary.total?<><ShieldAlert/><div><strong>Foram encontradas {data.summary.total} ocorrência(s) para análise.</strong><span>Nenhuma correção foi aplicada automaticamente. Abra o módulo indicado e confira os registros antes de alterar saldos.</span></div></>:<><BadgeCheck/><div><strong>Todos os cruzamentos estão consistentes.</strong><span>As rotinas financeiras e de estoque conferem no momento desta verificação.</span></div></>}<small>Verificado em {dateTime.format(new Date(data.checkedAt))}</small></section>}
    <section className="reconciliation-layout"><aside className="reconciliation-checks"><header><span className="section-kicker">VERIFICAÇÕES</span><h2>Rotinas conferidas</h2></header>{data?.checks.map(check=><button key={check.code} className={check.status==="OK"?"ok":"issue"} onClick={()=>{setModule(check.module);setSearch(check.title);}}><span>{check.status==="OK"?<BadgeCheck/>:<AlertTriangle/>}<b>{check.title}</b></span><small>{check.status==="OK"?"Sem divergências":`${check.issueCount} ocorrência(s)`}</small></button>)}{loading&&<div className="registry-loading"><LoaderCircle className="spin"/>Conferindo...</div>}</aside>
      <div className="reconciliation-results"><section className="reconciliation-toolbar"><label><Search size={17}/><input placeholder="Buscar ocorrência..." value={search} onChange={event=>setSearch(event.target.value)}/></label><select value={module} onChange={event=>setModule(event.target.value as Module|"TODOS")}><option value="TODOS">Todos os módulos</option>{Object.entries(moduleLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={severity} onChange={event=>setSeverity(event.target.value as typeof severity)}><option value="TODOS">Todas as prioridades</option><option value="CRITICO">Críticas</option><option value="ALERTA">Alertas</option></select>{(search||module!=="TODOS"||severity!=="TODOS")&&<button className="text-button" onClick={()=>{setSearch("");setModule("TODOS");setSeverity("TODOS");}}>Limpar</button>}</section>
        <section className="reconciliation-list">{error?<div className="empty-state">{error}</div>:loading?<div className="registry-loading"><LoaderCircle className="spin"/>Analisando as rotinas...</div>:!issues.length?<div className="reconciliation-empty"><BadgeCheck/><h2>Nenhuma ocorrência neste filtro</h2><p>Os cruzamentos selecionados estão consistentes.</p></div>:issues.map(issue=><article key={issue.id} className={issue.severity==="CRITICO"?"critical":"warning"}><div className="reconciliation-icon">{issue.module==="ESTOQUE"?<Boxes/>:issue.module==="COMPRAS"?<ShoppingCart/>:issue.severity==="CRITICO"?<ShieldAlert/>:<AlertTriangle/>}</div><div><header><span>{moduleLabels[issue.module]}</span><b>{issue.severity==="CRITICO"?"Crítica":"Alerta"}</b></header><h3>{issue.title}</h3><strong>{issue.reference}</strong><p>{issue.description}</p><div className="reconciliation-values"><span>Esperado <b>{number.format(issue.expected)}</b></span><span>Encontrado <b>{number.format(issue.actual)}</b></span><span>Diferença <b>{number.format(issue.actual-issue.expected)}</b></span></div></div><Link href={moduleLinks[issue.module]} title={`Abrir ${moduleLabels[issue.module]}`}><ChevronRight/></Link></article>)}</section>
      </div></section>
  </main></div>;
}
