"use client";

import { BarChart3, Bike, CalendarDays, ChevronDown, ChevronUp, Download, LoaderCircle, Menu, Search, ShoppingCart } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";

type ReportType = "sales" | "vehicles" | "purchases";
type Item = { name:string;type?:string;quantity:number;unitPrice?:number;unitCost?:number;total:number };
type ReportRow = { id:string;number?:string;date:string;customer?:string;plate?:string;model?:string;mechanic?:string;paymentMethod?:string;total:number;discount?:number;itemCount:number;quantity?:number;items:Item[];status?:string;mileage?:number|null;notes?:string;supplier?:string;documentNumber?:string;competenceDate?:string };
type ReportPayload = { report:ReportType;rows:ReportRow[];summary:Record<string,number> };

const money = new Intl.NumberFormat("pt-BR", { style:"currency",currency:"BRL" });
const number = new Intl.NumberFormat("pt-BR", { maximumFractionDigits:3 });
const date = new Intl.DateTimeFormat("pt-BR", { timeZone:"UTC" });
const formatDate = (value?:string) => value ? date.format(new Date(`${value}T00:00:00Z`)) : "—";
const csvCell = (value:unknown) => `"${String(value ?? "").replaceAll('"','""')}"`;

const reportMeta: Record<ReportType,{label:string;description:string}> = {
  sales:{label:"Vendas",description:"Pedidos concluídos e valores vendidos"},
  vehicles:{label:"Veículos",description:"Ocorrências e serviços por placa"},
  purchases:{label:"Compras",description:"Entradas de mercadoria e fornecedores"},
};

export function ReportsPage() {
  const [report,setReport]=useState<ReportType>("sales");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [search,setSearch]=useState("");const [appliedSearch,setAppliedSearch]=useState("");const [data,setData]=useState<ReportPayload>();const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [expanded,setExpanded]=useState<string>();const [mobileMenu,setMobileMenu]=useState(false);
  const load=useCallback(async(type:ReportType=report,signal?:AbortSignal)=>{setLoading(true);setError("");try{const params=new URLSearchParams({report:type});if(from)params.set("from",from);if(to)params.set("to",to);if(appliedSearch)params.set("search",appliedSearch);const response=await fetch(`/api/reports?${params}`,{signal});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível carregar o relatório.");setData(payload);setExpanded(undefined);}catch(caught){if(caught instanceof Error&&caught.name!=="AbortError"){setError(caught.message);setData(undefined);}}finally{if(!signal?.aborted)setLoading(false);}},[report,from,to,appliedSearch]);
  useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>load(report,controller.signal));return()=>controller.abort();},[load,report]);
  const statCards=useMemo(()=>{const summary=data?.summary??{};return report==="sales"?[["Vendas",summary.count??0],["Faturamento",money.format(summary.total??0)],["Descontos",money.format(summary.discount??0)],["Itens vendidos",number.format(summary.quantity??0)]]:report==="vehicles"?[["Ocorrências",summary.count??0],["Veículos",summary.vehicles??0],["Serviços e itens",summary.items??0],["Valor total",money.format(summary.total??0)]]:[["Compras",summary.count??0],["Total comprado",money.format(summary.total??0)],["Produtos distintos",summary.items??0],["Unidades",number.format(summary.quantity??0)]];},[report,data]);
  function selectReport(type:ReportType){setReport(type);setData(undefined);setExpanded(undefined);}
  function applyFilters(){setAppliedSearch(search.trim());if(search.trim()===appliedSearch)void load();}
  function clearFilters(){setFrom("");setTo("");setSearch("");setAppliedSearch("");}
  function exportCsv(){if(!data?.rows.length)return;const headers=report==="sales"?["Data","Pedido","Cliente","Placa","Veículo","Mecânico","Pagamento","Itens","Desconto","Total"]:report==="vehicles"?["Data","Pedido","Placa","Veículo","Cliente","KM","Mecânico","Status","Itens","Total","Observações"]:["Data","Competência","Fornecedor","Documento","Itens","Quantidade","Total","Status"];const rows=data.rows.map(row=>report==="sales"?[formatDate(row.date),row.number,row.customer,row.plate,row.model,row.mechanic,row.paymentMethod,row.itemCount,row.discount,row.total]:report==="vehicles"?[formatDate(row.date),row.number,row.plate,row.model,row.customer,row.mileage,row.mechanic,row.status,row.itemCount,row.total,row.notes]:[formatDate(row.date),formatDate(row.competenceDate),row.supplier,row.documentNumber,row.itemCount,row.quantity,row.total,row.status]);const csv="\uFEFF"+[headers,...rows].map(line=>line.map(csvCell).join(";")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`relatorio-${report}-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url);}
  return <div className="app-shell"><AppSidebar active="relatorios"/><main className="workspace registry-workspace"><header className="topbar registry-topbar"><button className="mobile-menu" onClick={()=>setMobileMenu(!mobileMenu)} aria-label="Abrir menu"><Menu/></button><div><p className="eyebrow">GESTÃO</p><h1>Relatórios</h1><p className="page-description">Consulte o histórico operacional e exporte os resultados para análise.</p></div><button className="secondary-button" onClick={exportCsv} disabled={!data?.rows.length}><Download size={17}/>Exportar CSV</button></header>
    {mobileMenu&&<div className="mobile-shortcuts registry-shortcuts"><Link href="/">Atendimento</Link><Link href="/estoque">Estoque</Link><Link href="/relatorios">Relatórios</Link></div>}
    <section className="report-tabs">{(Object.keys(reportMeta) as ReportType[]).map(type=><button className={report===type?"active":""} key={type} onClick={()=>selectReport(type)}>{type==="sales"?<BarChart3/>:type==="vehicles"?<Bike/>:<ShoppingCart/>}<span><b>{reportMeta[type].label}</b><small>{reportMeta[type].description}</small></span></button>)}</section>
    <section className="period-toolbar report-toolbar"><label><span>De</span><input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label><span>Até</span><input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><label className="report-search"><span>Buscar</span><div><Search size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} onKeyDown={event=>event.key==="Enter"&&applyFilters()} placeholder={report==="purchases"?"Fornecedor, documento ou produto":"Cliente, pedido, placa ou veículo"}/></div></label><button className="primary-button" onClick={applyFilters}><Search size={17}/>Buscar</button><button className="text-button" onClick={clearFilters}>Limpar filtros</button></section>
    <section className="operations-stats report-stats">{statCards.map(([label,value],index)=><div key={String(label)}><CalendarDays/><span>{label}</span><strong>{value}</strong>{index===0&&data?.rows.length===1000&&<small>Limite de 1.000 registros</small>}</div>)}</section>
    {error&&<p className="form-error">{error}</p>}
    <section className="registry-panel report-panel"><div className="operations-title"><div><span className="section-kicker">HISTÓRICO</span><h2>{reportMeta[report].label}</h2></div><span>{data?.rows.length??0} registro(s)</span></div>{loading?<div className="registry-loading"><LoaderCircle className="spin"/>Carregando relatório...</div>:!data?.rows.length?<div className="empty-state">Nenhum registro encontrado para os filtros informados.</div>:<div className="registry-table-wrap"><table className="registry-table report-table"><thead>{report==="sales"?<tr><th>Data / pedido</th><th>Cliente / veículo</th><th>Mecânico</th><th>Pagamento</th><th>Itens</th><th>Total</th><th></th></tr>:report==="vehicles"?<tr><th>Data / pedido</th><th>Placa / veículo</th><th>Cliente</th><th>KM</th><th>Itens</th><th>Total</th><th></th></tr>:<tr><th>Data</th><th>Fornecedor</th><th>Documento</th><th>Itens</th><th>Quantidade</th><th>Total</th><th></th></tr>}</thead><tbody>{data.rows.map(row=><ReportRowView key={row.id} row={row} type={report} expanded={expanded===row.id} toggle={()=>setExpanded(current=>current===row.id?undefined:row.id)}/>)}</tbody></table></div>}</section>
  </main></div>;
}

function ReportRowView({row,type,expanded,toggle}:{row:ReportRow;type:ReportType;expanded:boolean;toggle:()=>void}) {
  return <>{type==="sales"?<tr><td data-label="Data / pedido"><strong>{formatDate(row.date)}</strong><small className="table-note">#{row.number}</small></td><td data-label="Cliente / veículo"><strong>{row.customer}</strong><small className="table-note">{[row.plate,row.model].filter(Boolean).join(" · ")||"Sem veículo"}</small></td><td data-label="Mecânico">{row.mechanic||"—"}</td><td data-label="Pagamento">{row.paymentMethod||"—"}</td><td data-label="Itens">{row.itemCount}</td><td data-label="Total"><strong>{money.format(row.total)}</strong>{Boolean(row.discount)&&<small className="table-note">Desconto {money.format(row.discount!)}</small>}</td><td data-label="Detalhes"><button className="report-expand" onClick={toggle} aria-label="Ver itens">{expanded?<ChevronUp/>:<ChevronDown/>}</button></td></tr>:type==="vehicles"?<tr><td data-label="Data / pedido"><strong>{formatDate(row.date)}</strong><small className="table-note">#{row.number}</small></td><td data-label="Placa / veículo"><strong>{row.plate}</strong><small className="table-note">{row.model||"Modelo não informado"}</small></td><td data-label="Cliente">{row.customer}</td><td data-label="KM">{row.mileage==null?"—":number.format(row.mileage)}</td><td data-label="Itens">{row.itemCount}</td><td data-label="Total"><strong>{money.format(row.total)}</strong></td><td data-label="Detalhes"><button className="report-expand" onClick={toggle} aria-label="Ver ocorrência">{expanded?<ChevronUp/>:<ChevronDown/>}</button></td></tr>:<tr><td data-label="Data"><strong>{formatDate(row.date)}</strong><small className="table-note">Competência {formatDate(row.competenceDate)}</small></td><td data-label="Fornecedor"><strong>{row.supplier}</strong></td><td data-label="Documento">{row.documentNumber||"—"}</td><td data-label="Itens">{row.itemCount}</td><td data-label="Quantidade">{number.format(row.quantity??0)}</td><td data-label="Total"><strong>{money.format(row.total)}</strong></td><td data-label="Detalhes"><button className="report-expand" onClick={toggle} aria-label="Ver itens">{expanded?<ChevronUp/>:<ChevronDown/>}</button></td></tr>}{expanded&&<tr className="report-detail-row"><td colSpan={7}><div className="report-detail">{type==="vehicles"&&<header><span><b>Status:</b> {row.status?.replaceAll("_"," ")}</span><span><b>Mecânico:</b> {row.mechanic||"Não informado"}</span>{row.notes&&<span><b>Observações:</b> {row.notes}</span>}</header>}<div>{row.items.map((item,index)=><p key={`${row.id}-${index}`}><span><b>{item.name||"Produto removido"}</b>{item.type&&<small>{item.type}</small>}</span><span>{number.format(Number(item.quantity))} × {money.format(Number(item.unitPrice??item.unitCost??0))}</span><strong>{money.format(Number(item.total))}</strong></p>)}</div>{!row.items.length&&<span className="empty-compact">Nenhum item detalhado.</span>}</div></td></tr>}</>;
}
