"use client";
import { KeyRound, LoaderCircle, Menu, Pencil, Plus, ShieldCheck, UserCheck, Users, X } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { AppSidebar } from "@/components/app-sidebar";
import { permissionIds, type Permission } from "@/lib/auth-shared";

type User = { id: string; name: string; email: string; role: string; permissions: Permission[]; active: boolean; last_login_at?: string; created_at: string };
const labels: Record<Permission, string> = { atendimento: "Atendimento", compras: "Compras", receber: "Contas a receber", conferencia: "Conferência", financeiro: "Financeiro", estoque: "Estoque", clientes: "Clientes", veiculos: "Veículos", produtos: "Produtos e serviços", mecanicos: "Mecânicos", usuarios: "Usuários" };
const dateTime = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" });

export function UsersPage() {
  const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [mobileMenu, setMobileMenu] = useState(false);
  const [editing, setEditing] = useState<User | null | undefined>(undefined); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState("OPERADOR"); const [permissions, setPermissions] = useState<Permission[]>(["atendimento"]); const [active, setActive] = useState(true);
  async function load(signal?: AbortSignal) { const response = await fetch("/api/users", { signal }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Não foi possível carregar os usuários."); setUsers(payload.users); }
  useEffect(() => { const controller = new AbortController(); fetch("/api/users", { signal: controller.signal }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Não foi possível carregar os usuários."); setUsers(payload.users); }).catch((caught) => { if (caught instanceof Error && caught.name !== "AbortError") setError(caught.message); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  function open(user?: User) { setEditing(user ?? null); setName(user?.name ?? ""); setEmail(user?.email ?? ""); setPassword(""); setRole(user?.role ?? "OPERADOR"); setPermissions(user?.permissions ?? ["atendimento"]); setActive(user?.active ?? true); setError(""); }
  function toggle(permission: Permission) { setPermissions((current) => current.includes(permission) ? current.filter((item) => item !== permission) : [...current, permission]); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(editing ? `/api/users/${editing.id}` : "/api/users", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name,email,password,role,permissions,active }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Não foi possível salvar o usuário."); await load(); setEditing(undefined); setNotice(editing ? "Usuário atualizado. O novo acesso valerá no próximo login." : "Usuário criado com sucesso."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível salvar."); } finally { setSaving(false); } }
  return <div className="app-shell"><AppSidebar active="usuarios" /><main className="workspace registry-workspace"><header className="topbar registry-topbar"><button className="mobile-menu" onClick={() => setMobileMenu(!mobileMenu)}><Menu /></button><div><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Usuários e acessos</h1><p className="page-description">Defina quem pode entrar e quais áreas cada pessoa pode utilizar.</p></div><button className="primary-button" onClick={() => open()}><Plus size={18} /> Novo usuário</button></header>{mobileMenu && <div className="mobile-shortcuts registry-shortcuts"><Link href="/">Atendimento</Link><Link href="/usuarios">Usuários</Link></div>}
    <section className="operations-stats"><div><Users /><span>Usuários</span><strong>{users.length}</strong></div><div><UserCheck /><span>Ativos</span><strong>{users.filter((user) => user.active).length}</strong></div><div><ShieldCheck /><span>Administradores</span><strong>{users.filter((user) => user.role === "ADMIN").length}</strong></div></section>
    <section className="registry-panel">{loading ? <div className="registry-loading"><LoaderCircle className="spin" /> Carregando usuários...</div> : error && !users.length ? <div className="empty-state">{error}</div> : <div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>Usuário</th><th>Papel</th><th>Áreas liberadas</th><th>Último acesso</th><th>Status</th><th>Ações</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td data-label="Usuário"><strong>{user.name}</strong><small className="table-note">{user.email}</small></td><td data-label="Papel">{user.role}</td><td data-label="Áreas"><span className="permission-count">{user.role === "ADMIN" ? "Todas" : `${user.permissions.length} área(s)`}</span></td><td data-label="Último acesso">{user.last_login_at ? dateTime.format(new Date(user.last_login_at)) : "Nunca acessou"}</td><td data-label="Status"><span className={`registry-status ${user.active ? "active" : "inactive"}`}>{user.active ? "Ativo" : "Inativo"}</span></td><td data-label="Ações"><button className="table-action" onClick={() => open(user)}><Pencil size={15} /> Editar</button></td></tr>)}</tbody></table></div>}</section></main>
    {editing !== undefined && <div className="modal-backdrop"><section className="registry-modal user-modal"><header className="modal-header"><div><span className="section-kicker">ACESSO</span><h2>{editing ? "Editar usuário" : "Novo usuário"}</h2></div><button className="icon-button" onClick={() => setEditing(undefined)}><X /></button></header><form className="registry-form" onSubmit={save}><div className="form-grid registry-form-grid"><label className="field"><span>Nome *</span><input value={name} onChange={(event) => setName(event.target.value)} required /></label><label className="field"><span>E-mail *</span><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label className="field"><span>Papel *</span><select value={role} onChange={(event) => setRole(event.target.value)}><option value="OPERADOR">Operador</option><option value="FINANCEIRO">Financeiro</option><option value="ESTOQUE">Estoque</option><option value="ADMIN">Administrador</option></select></label><label className="field"><span>{editing ? "Nova senha (opcional)" : "Senha *"}</span><input type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} required={!editing} /></label><label className="checkbox-field"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} /> Usuário ativo</label></div><fieldset className="permission-grid" disabled={role === "ADMIN"}><legend><KeyRound size={17} /> Áreas permitidas {role === "ADMIN" && "— acesso total"}</legend>{permissionIds.filter((permission) => permission !== "usuarios").map((permission) => <label key={permission}><input type="checkbox" checked={role === "ADMIN" || permissions.includes(permission)} onChange={() => toggle(permission)} />{labels[permission]}</label>)}</fieldset>{error && <p className="form-error">{error}</p>}<footer className="modal-actions"><button className="secondary-button" type="button" onClick={() => setEditing(undefined)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={18} /> : <ShieldCheck size={18} />}Salvar usuário</button></footer></form></section></div>}{notice && <button className="toast" onClick={() => setNotice("")}>{notice}</button>}</div>;
}
